import type { Metadata } from 'next';
import '@/app/globals.css';
import RootLayout from '@/components/root-layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const Layout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <RootLayout>{children}</RootLayout>
    </html>
  );
};

export default Layout;
